curl -X POST -H "Content-Type: application/json" -d '{
 "from": "akjflw",
  "to":"fjlakdj",
   "amount": 3
}' "http://localhost:5000/txion"

###

curl -X POST -H "Content-Type: application/json" -d '{
 "from": "fjlakdj",
  "to":"akjflw",
   "amount": 40
}' "http://localhost:5000/txion"

###

curl  GET  -H "http://localhost:5000/mine"